### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by roose** [jdrgomes/awesome-postcss#14]
In **Podcasts**:
Issue 24: The most stylish szhimator - (Russian)
stylish a play on words from the _cascading styles_
_szhimator_ is _minificator_

**Comment by jdrgoms** [comment]
@roose You can make the correction?

**Comment by roose** [comment]
@jjaderg I don't know English well enough to play with words, 
"The most stylish minificator" or "The most CSS minificator" :smiley: 

By the way, minificator or minifier?

**Comment by jdrgoms** [comment]
Relax, I am not expert in English. However, minifier seems to be most ideal. Even the minify is called as Minifier.

**Comment by roose** [comment]
@jjaderg I create PR #15
