### ISSUE TITLE
Validate links

### ISSUE THREAD

**Issue by mvfsillva** [jdrgomes/awesome-postcss#3]
Hey Jader, how you doing?

Would be nice, if we have a link validator for we know if that link continues online or not, what do you think?

**Comment by jdrgoms** [comment]
what's up, bro
It really is important to analyse the links, you can do this?

**Comment by mvfsillva** [comment]
let's go bro

**Comment by jdrgoms** [comment]
Something that can help you :grin:
https://github.com/dkhamsing/awesome_bot

**Comment by mvfsillva** [comment]
Great ;]
